server:
  port: 8585

management:
  endpoints:
    web:
      exposure:
        include: "*"

        
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{15}){cyan}  [%clr(%X{cx}){blue}] %clr(:){faint} %m%n%wEx"

  level:
    com:
      checkmarx:
        flow: INFO
        # sdk: TRACE
    # org:
    #   apache:
    #     http:
    #       wire: TRACE
    #   springframework:
    #     web:
    #       client:
    #         RestTemplate: TRACE         
    
cx-flow:
  contact: admin@test.com
  bug-tracker: Azure
  bug-tracker-impl:
    - CxXml
    - Json
    - GitLab
    - GitHub
    - Csv
    - Azure
  branches:
    - master

github:
    webhook-token: # put the value you provided to GitHub when creating the webhook
    token: # put a GitHub personal access token here so cx-flow can write feedback into the pull request
    url: https://github.com
    api-url: https://api.github.com/repos/
    block-merge: true


checkmarx:
  username: # TODO: put the SAST account username here
  password: # TODO: put the SAST account password here
  base-url: # TODO: put the URL of your SAST instance here
  team: # TODO: put the SAST team here
  scan-preset: # TODO: Put your desired scan preset here

  version: 9.0
  client-id: resource_owner_client
  scope: access_control_api sast_rest_api  
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  url: ${checkmarx.base-url}/cxrestapi
  multi-tenant: false
  incremental: false
  configuration: Default Configuration
  scan-timeout: 120
#WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
  portal-package: checkmarx.wsdl.portal
  preserve-xml: true
  jira-project-field:
  jira-custom-field:
  jira-issuetype-field:
  jira-assignee-field:

# This is configured for the ADO "Basic" project.  You may need to modify "closed-status" and "open-status"
# to match your project configuration.
azure:
  # webhook-token: this is omitted because webhooks are coming from github in this example
  token: # TODO: provide an access token with access to create issues
  url: # TODO: Provide the organization name for the URL: https://dev.azure.com/{organization}
  issue-type: issue
  api-version: 5.0
  closed-status: Done
  open-status: To Do
  false-positive-label: false-positive
  

  


