server:
  port: ${CXFLOW_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

        
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{15}){cyan}  [%clr(%X{cx}){blue}] %clr(:){faint} %m%n%wEx"

  level:
    com:
      checkmarx:
        flow: info
         
cx-flow:
  bug-tracker: Jira
  bug-tracker-impl:
    - CxXml
    - Json
    - GitLab
    - GitHub
    - Csv
  branches:
    - master

github:
  webhook-token: # TODO: put the value you provided to GitHub when creating the webhook
  token: # TODO: put a GitHub personal access token here so cx-flow can write feedback into the pull request
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  block-merge: true
  detailed: false

checkmarx:
  username: # TODO: put the SAST account username here
  password: # TODO: put the SAST account password here
  base-url: # TODO: put the URL of your SAST instance here
  team: # TODO: put the SAST team here
  scan-preset: # TODO: Put your desired scan preset here

  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  url: ${checkmarx.base-url}/cxrestapi
  multi-tenant: false
  incremental: false
  configuration: Default Configuration
  scan-timeout: 120
#WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
  portal-package: checkmarx.wsdl.portal
  preserve-xml: true
  jira-project-field:
  jira-custom-field:
  jira-issuetype-field:
  jira-assignee-field:
  
  
jira:
  username: # TODO: put the JIRA account username here
  token: # TODO: put the JIRA account password or token here
  project: # TODO: put the name of the JIRA project where tickets will be created here


  url: http://jira-server:8080
  issue-type: Bug
  priorities:
    High: High
    Medium: Medium
    Low: Low
    Informational: Lowest
  open-transition: In Review
  close-transition: Done
  open-status:
    - To Do
    - In Progress
    - In Review
  closed-status:
    - Done
  fields:
    - type: result
      name: application
      jira-field-name: Application
      jira-field-type: label
    - type: result
      name: cve
      jira-field-name: CVEs
      jira-field-type: label
    - type: result
      name: cwe
      jira-field-name: CWEs
      jira-field-type: label
    - type: result
      name: category
      jira-field-name: Category
      jira-field-type: label
    - type: result
      name: loc
      jira-field-name: LOC
      jira-field-type: label


