FROM openjdk:8u212-jdk-stretch@sha256:dfa24d97c724814b56b3735fb0b2570576f0dc1036c8060e4913b6b95f1da0aa

RUN apt-get update && \
apt-get install -y maven gradle && \
apt-get clean

ENV AGENT_TAG=jdk8

COPY agent_entry.sh /
COPY logging.properties /

COPY --from=checkmarxts/cxflow:latest /*.jar /

RUN chmod +x /agent_entry.sh && \
    mkdir /workspace && \
    chmod ugo+rwx /workspace

ENTRYPOINT ["/agent_entry.sh"]
