FROM openjdk:11.0-jdk-stretch

RUN apt-get update && \
apt-get install -y maven gradle && \
apt-get clean

ENV AGENT_TAG=jdk11

COPY agent_entry.sh /
COPY logging.properties /

COPY --from=checkmarxts/cxflow:latest /*.jar /

RUN chmod +x /agent_entry.sh && \
    mkdir /workspace && \
    chmod ugo+rwx /workspace

ENTRYPOINT ["/agent_entry.sh"]